### ISSUE TITLE
Stream bitrate

### ISSUE THREAD

**Issue by louiscenter** [mafintosh/hypervision#5]
`hypervision` is great! Looking forward to a future of p2p video streaming ^__^

What bitrate is video broadcasted at, and is this setting configurable?

**Comment by yoshuawuyts** [comment]
Looks like we're wrapping https://github.com/mafintosh/media-recorder-stream which in turn wraps https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder which in the constructor can have the bitrate set https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/MediaRecorder.

Looks like you can pass the options directly to `MediaRecorder` by setting the second argument in `media-recorder-stream` - https://github.com/mafintosh/media-recorder-stream/blob/master/index.js#L36; having an interface to set this through the `hypervision` UI would be neat I reckon (:

**Comment by louiscenter** [comment]
@yoshuawuyts - thanks for providing leads for this.

I managed to incorporate this into a new PR I just submitted, which includes a feature allowing you to toggle the bitrate of your broadcast.

You can check it out at https://github.com/mafintosh/hypervision/pull/7

Cheers!
